#!/usr/bin/env bash

# The ssh keys were generated by
# ssh-keygen -f keys/id_rsa -t rsa -b 4096 -C "ubuntu@my-app-incloud.com" -N ""

echo 'Getting public ssh key'
cat keys/id_rsa.pub > keys/authorized_keys

function exportVariables() {
    echo 'INFO:export aws credential variables'
    for var in $(cat my-app.properties); do
        export $var
    done
}

function packerExecution() {
    packer validate 'packer/template.json'
    packer build -force -color=false 'packer/template.json'
}

function terraformExecution() {
    cd terraform
    terraform init -force-copy
    terraform plan
    terraform apply -auto-approve
    terraform output -no-color -json > ../public-access.json
}

exportVariables
python replace_packer.py
packerExecution

export AWS_AMI_ID=$(aws ec2 describe-images --region ${AWS_DEFAULT_REGION}  --filters "Name=tag-key,Values=Name,Name=tag-value,Values=${AWS_LABEL}" --query 'Images[*].{id:ImageId}' | jq .[].id)

echo 'INFO:Starting replace envs on terraform variables'
cat terraform/variables.tf.tpl \
    | sed "s/<AWS_SECRET_ACCESS_KEY>/${AWS_SECRET_ACCESS_KEY}/g" \
    | sed "s/<AWS_DEFAULT_REGION>/${AWS_DEFAULT_REGION}/g" \
    | sed "s/<AWS_ACCESS_KEY_ID>/${AWS_ACCESS_KEY_ID}/g" \
    | sed "s/<AWS_AMI_ID>/${AWS_AMI_ID}/g" \
    | sed "s/<AWS_LABEL>/${AWS_LABEL}/g"  \
    > terraform/provider.tf

echo "The new AWS AMI is: ${AWS_AMI_ID}"
terraformExecution